eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-regitry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://dev-27796049.okta.com/oauth2/default
        #audience: api://default
